[images]
git-tree-sha1 = "5f6e78f15fd5bea320c1e5b9daf5a0062f185215"
lazy = true

    [[images.download]]
    sha256 = "2104ac05ff5309a7fe50e7a393c7b92e92a895f1dabeb4dab2487b3508883c58"
    url = "https://github.com/wookay/UnsplashImages.jl/releases/download/v0.1.0-artifacts/images.tar.gz"
