[images]
git-tree-sha1 = "d80d3f1796612f2974dce8caf46da7fd8038fa56"
lazy = true

    [[images.download]]
    sha256 = "53eea9617bc3e996d433f77cae96838dbc7cc7f6a1afb58e704607f0d830298c"
    url = "https://github.com/wookay/UnsplashImages.jl/releases/download/v0.1.1-artifacts/images.tar.gz"
