#
# An easy image database
#
# the key has to match the filename
# then one can use the sub fields
#
# name     - filename in the images directory
# title
# author   – original author (if known)
# url      - origin url (if known)
# license  - license
#
# none of these fields is required.

[[images]]
name = "yannic-laderach-Dqx4XWuXu7w-unsplash.small.jpg"
title = "woman standing on rock facing forest photo"
author = "Yannic Läderach"
url = "https://unsplash.com/photos/Dqx4XWuXu7w"
license = "Free to use under the Unsplash License"

[[images]]
name = "yannic-laderach-Dqx4XWuXu7w-unsplash.small.u2net_human_seg.png"
title = "u2net_human_seg - woman standing on rock facing forest photo"

[[images]]
name = "tyler-nix-k5R4cdIAiuk-unsplash.small.jpg"
title = "woman in white long sleeve shirt and blue denim jeans holding pink and black handbag photo"
author = "Tyler Nix"
url = "https://unsplash.com/photos/k5R4cdIAiuk"
license = "Free to use under the Unsplash License"
